## src: ./configs..textlint/dict/prh-my-settings.yml
## @(#) : textlint prh dictionary for user settings
#
# @version 1.0.0
# @author  atsushifx <https://github.com/atsushifx>
# @since   2025-05-14
# @license MIT
#
# @desc<<
# textlint prh user dictionary for custom proofreading rules.
# Intended to complement shared base dictionary.
#<<

## dict start
rules:
# - expected: 修正後の表現
#   pattern: 修正対象（正規表現も可）
#   specs:
#     - from: 誤り
#       to:   正しい表現
## end of dict
